import { PathData } from './data';

export const MOCK_RUNS: PathData[] = [
  {
    id: 'path-1',
    title: '[Demo] Resolved Pytest async timeout bug in 12s',
    description: 'Diagnosed async loop closure leak in test_runner.py, reflected on AST context, generated patch, and verified sandbox tests.',
    status: 'COMPLETED',
    durationMs: 12400,
    tokens: 18400,
    cost: 0.038,
    tps: 112.4,
    elevationDepth: 7,
    modelFamily: 'Claude 3.5 Sonnet',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    project: 'code-refactor',
    env: 'production',
    qualityScore: 87,
    version: 'v1.4',
    isDemo: true,
    promptTokens: 5000,
    completionTokens: 13400,
    input: JSON.stringify({ prompt: "Fix pytest timeout error in async handler test_auth_flow()", target: "tests/test_auth.py" }),
    output: JSON.stringify({ result: "Generated patch for async loop closure leak. All 14 tests passing.", patch_file: "test_runner.py" }),
    agent: {
      id: 'agent-code',
      name: 'CodeRefactor Agent',
      framework: 'Custom',
    },
    spans: [
      {
        id: 'sp_01',
        spanId: 'span_01',
        name: 'Prompt Ingestion & AST Parsing',
        type: 'agent',
        status: 'SUCCESS',
        latencyMs: 180,
        tokens: 800,
        cost: 0.0016,
        model: 'claude-3.5-sonnet',
        provider: 'anthropic',
        inputTokens: 400,
        outputTokens: 400,
        rawInput: JSON.stringify({ prompt: "Fix pytest timeout error in async handler test_auth_flow()", target: "tests/test_auth.py" }, null, 2),
        rawOutput: JSON.stringify({ parsedAST: { functions: ["test_auth_flow"], imports: ["pytest", "asyncio"] } }, null, 2)
      },
      {
        id: 'sp_02',
        spanId: 'span_02',
        parentSpanId: 'span_01',
        name: 'SerpAPI Pytest Async Docs Search',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 420,
        tokens: 2400,
        cost: 0.0048,
        inputTokens: 200,
        outputTokens: 2200,
        rawInput: JSON.stringify({ query: "pytest-asyncio fixture scope loop closed event loop leak fix" }, null, 2),
        rawOutput: JSON.stringify({ results: [{ title: "pytest-asyncio: event_loop fixture scope", url: "https://docs.pytest.org/..." }] }, null, 2)
      },
      {
        id: 'sp_03',
        spanId: 'span_03',
        parentSpanId: 'span_02',
        name: 'AST Loop Contention Analysis',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 1200,
        tokens: 3400,
        cost: 0.0068,
        model: 'claude-3.5-sonnet',
        provider: 'anthropic',
        inputTokens: 1800,
        outputTokens: 1600,
        rawInput: JSON.stringify({ system: "Analyze the following AST for potential async loop contention issues", code: "async def test_auth_flow(): ..." }, null, 2),
        rawOutput: JSON.stringify({ analysis: "Found unclosed event loop in fixture scope. The loop_scope parameter needs to be set to 'function' to prevent cross-test contamination." }, null, 2)
      },
      {
        id: 'sp_04',
        spanId: 'span_04',
        parentSpanId: 'span_01',
        name: 'Playwright Sandbox Test Verification',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 7600,
        tokens: 3200,
        cost: 0.0064,
        inputTokens: 800,
        outputTokens: 2400,
        rawInput: JSON.stringify({ command: "pytest tests/test_auth.py -v --timeout=30" }, null, 2),
        rawOutput: JSON.stringify({ passed: 14, failed: 0, duration_s: 7.2 }, null, 2)
      },
      {
        id: 'sp_05',
        spanId: 'span_05',
        parentSpanId: 'span_04',
        name: 'VectorDB Long-Term Memory Recall',
        type: 'retrieval',
        status: 'SUCCESS',
        latencyMs: 2400,
        tokens: 1200,
        cost: 0.0024,
        inputTokens: 200,
        outputTokens: 1000,
        rawInput: JSON.stringify({ query: "similar async fixture bugs in this project" }, null, 2),
        rawOutput: JSON.stringify({ matches: [{ id: "mem_42", content: "Fixed similar issue in test_api.py on 2024-01-15" }] }, null, 2)
      },
      {
        id: 'sp_06',
        spanId: 'span_06',
        parentSpanId: 'span_05',
        name: 'Claude 3.5 Sonnet Patch Generator',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 3800,
        tokens: 6600,
        cost: 0.0132,
        model: 'claude-3.5-sonnet',
        provider: 'anthropic',
        inputTokens: 3200,
        outputTokens: 3400,
        rawInput: JSON.stringify({ system: "Generate a code patch based on the analysis", context: "AST analysis results + similar past fixes" }, null, 2),
        rawOutput: JSON.stringify({ patch: "diff --git a/tests/test_auth.py\n- @pytest.fixture\n+ @pytest.fixture(scope='function')\n  async def event_loop():\n      loop = asyncio.new_event_loop()\n      yield loop\n+     loop.close()" }, null, 2)
      },
      {
        id: 'sp_07',
        spanId: 'span_07',
        parentSpanId: 'span_06',
        name: 'Final Code Diff & Output',
        type: 'chain',
        status: 'SUCCESS',
        latencyMs: 650,
        tokens: 2400,
        cost: 0.0048,
        inputTokens: 1200,
        outputTokens: 1200
      }
    ]
  },
  {
    id: 'path-2',
    title: '[Demo] Autonomous E-Commerce Checkout Pipeline',
    description: 'Extracted product specs, navigated checkout steps via headless browser, filled shipping forms, and executed payment authorization.',
    status: 'COMPLETED',
    durationMs: 18200,
    tokens: 32100,
    cost: 0.031,
    tps: 145.2,
    elevationDepth: 5,
    modelFamily: 'GPT-4o',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    project: 'browser-automation',
    env: 'production',
    qualityScore: 92,
    version: 'v2.1',
    isDemo: true,
    promptTokens: 10000,
    completionTokens: 22100,
    input: JSON.stringify({ task: "Purchase item SKU-4821 with express shipping", user_profile: "test_user_01" }),
    output: JSON.stringify({ order_id: "ORD-98421", status: "confirmed", total: "$49.99" }),
    agent: {
      id: 'agent-browser',
      name: 'AutoBrowser Runner',
      framework: 'CrewAI',
    },
    spans: [
      {
        id: 'sp_21',
        spanId: 'span_21',
        name: 'User Intent Parser',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 210,
        tokens: 1200,
        cost: 0.0024,
        model: 'gpt-4o',
        provider: 'openai'
      },
      {
        id: 'sp_22',
        spanId: 'span_22',
        parentSpanId: 'span_21',
        name: 'Playwright DOM Selector Agent',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 11100,
        tokens: 8400,
        cost: 0.0094
      },
      {
        id: 'sp_23',
        spanId: 'span_23',
        parentSpanId: 'span_22',
        name: 'Form Field Autocomplete Generator',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 1200,
        tokens: 4200,
        cost: 0.0084,
        model: 'gpt-4o'
      },
      {
        id: 'sp_24',
        spanId: 'span_24',
        parentSpanId: 'span_23',
        name: 'Stripe Sandbox Payment Exec',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 1600,
        tokens: 1800,
        cost: 0.0036
      },
      {
        id: 'sp_25',
        spanId: 'span_25',
        parentSpanId: 'span_24',
        name: 'Order Confirmation Synthesizer',
        type: 'chain',
        status: 'SUCCESS',
        latencyMs: 4090,
        tokens: 16500,
        cost: 0.0072
      }
    ]
  },
  {
    id: 'path-3',
    title: '[Demo] Deep Research: Market Analysis Breakdown',
    description: 'Multi-step web search and paper synthesis pipeline for EV battery manufacturing cost projections through 2030.',
    status: 'FAILED',
    durationMs: 42100,
    tokens: 94200,
    cost: 0.142,
    tps: 68.4,
    elevationDepth: 6,
    modelFamily: 'Claude 3.5 Sonnet',
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    project: 'research',
    env: 'production',
    qualityScore: 63,
    version: 'v1.0',
    isDemo: true,
    error: 'Synthesis Timeout: Exceeded maximum allowed latency threshold (40s)',
    errorType: 'TIMEOUT',
    promptTokens: 32000,
    completionTokens: 62200,
    agent: {
      id: 'agent-research',
      name: 'ResearchAgent',
      framework: 'LangChain',
    },
    spans: [
      {
        id: 'sp_31',
        spanId: 'span_31',
        name: 'Query Decomposition',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 850,
        tokens: 3200,
        cost: 0.0064,
        model: 'claude-3.5-sonnet'
      },
      {
        id: 'sp_32',
        spanId: 'span_32',
        parentSpanId: 'span_31',
        name: 'WebSearch: ArXiv Papers',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 1200,
        tokens: 12400,
        cost: 0.0268
      },
      {
        id: 'sp_33',
        spanId: 'span_33',
        parentSpanId: 'span_32',
        name: 'WebSearch: Competitor Analysis',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 1800,
        tokens: 14200,
        cost: 0.0240
      },
      {
        id: 'sp_34',
        spanId: 'span_34',
        parentSpanId: 'span_33',
        name: 'WebSearch: Market Size Data',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 2100,
        tokens: 18500,
        cost: 0.0260
      },
      {
        id: 'sp_35',
        spanId: 'span_35',
        parentSpanId: 'span_34',
        name: 'WebSearch: Pricing Models',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 3200,
        tokens: 16800,
        cost: 0.0280
      },
      {
        id: 'sp_36',
        spanId: 'span_36',
        parentSpanId: 'span_35',
        name: 'WebSearch: Final Synthesis Attempt',
        type: 'llm',
        status: 'FAILED',
        latencyMs: 22600,
        tokens: 29100,
        cost: 0.0088,
        diagnosticTag: 'PROMPT_DRIFT',
        diagnosticSummary: 'Context buffer exceeded 90k tokens causing attention degradation and subsequent timeout.',
        errorType: 'TIMEOUT',
        errorMessage: 'Connection closed by peer before full response streamed'
      }
    ]
  },
  {
    id: 'path-4',
    title: '[Demo] Customer Support Ticket Auto-Triage & Response',
    description: 'Ingested high-priority billing inquiry, queried Stripe records, verified plan eligibility, and drafted tailored response with discount offer.',
    status: 'COMPLETED',
    durationMs: 7800,
    tokens: 9400,
    cost: 0.028,
    tps: 189.1,
    elevationDepth: 4,
    modelFamily: 'GPT-4o',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    project: 'support',
    env: 'production',
    qualityScore: 84,
    version: 'v3.0',
    isDemo: true,
    promptTokens: 3400,
    completionTokens: 6000,
    agent: {
      id: 'agent-support',
      name: 'SupportTicket Agent',
      framework: 'LangChain',
    },
    spans: [
      {
        id: 'sp_41',
        spanId: 'span_41',
        name: 'Ticket Sentiment & Classification',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 320,
        tokens: 1400,
        cost: 0.0028,
        model: 'gpt-4o'
      },
      {
        id: 'sp_42',
        spanId: 'span_42',
        parentSpanId: 'span_41',
        name: 'Database: Billing Records Lookup',
        type: 'tool',
        status: 'FAILED',
        latencyMs: 5200,
        tokens: 800,
        cost: 0.0010,
        retryCount: 1,
        diagnosticTag: 'CIRCUIT_BREAKER_KILL',
        diagnosticSummary: 'Query timed out after 5000ms. Fallback replica lookup executed.'
      },
      {
        id: 'sp_43',
        spanId: 'span_43',
        parentSpanId: 'span_42',
        name: 'Database: Billing Records Lookup (Replica)',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 340,
        tokens: 1200,
        cost: 0.0020
      },
      {
        id: 'sp_44',
        spanId: 'span_44',
        parentSpanId: 'span_43',
        name: 'Response Composer & Tone Check',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 1400,
        tokens: 4800,
        cost: 0.0120,
        model: 'gpt-4o'
      },
      {
        id: 'sp_45',
        spanId: 'span_45',
        parentSpanId: 'span_44',
        name: 'Email Notification Dispatcher',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 940,
        tokens: 1200,
        cost: 0.0100
      }
    ]
  },
  {
    id: 'path-5',
    title: '[Demo] Microservice Migration Planner',
    description: 'Analyzed monolithic repo dependency graph, identified cyclic imports, and attempted automated Kubernetes manifest generation.',
    status: 'FAILED',
    durationMs: 34200,
    tokens: 58200,
    cost: 0.094,
    tps: 82.1,
    elevationDepth: 5,
    modelFamily: 'Claude 3.5 Sonnet',
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    project: 'devops-automation',
    env: 'staging',
    qualityScore: 50,
    version: 'v0.9',
    isDemo: true,
    error: 'Recursion Loop: Tool loop detected between Schema Fetch and Contention Resolver',
    errorType: 'TOOL_LOOP',
    promptTokens: 20000,
    completionTokens: 38200,
    agent: {
      id: 'agent-code',
      name: 'CodeRefactor Agent',
      framework: 'Custom',
    },
    spans: [
      {
        id: 'sp_51',
        spanId: 'span_51',
        name: 'Repository Structure Scanner',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 3200,
        tokens: 8400,
        cost: 0.0840
      },
      {
        id: 'sp_52',
        spanId: 'span_52',
        parentSpanId: 'span_51',
        name: 'Dependency Vulnerability Check',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 8400,
        tokens: 4200,
        cost: 0.0360
      },
      {
        id: 'sp_53',
        spanId: 'span_53',
        parentSpanId: 'span_52',
        name: 'Database Schema Fetch (Attempt 1)',
        type: 'tool',
        status: 'FAILED',
        latencyMs: 8000,
        tokens: 1200,
        cost: 0.0010,
        retryCount: 1,
        diagnosticTag: 'BAD_TOOL_SCHEMA',
        diagnosticSummary: 'Missing required foreign key constraints in payload'
      },
      {
        id: 'sp_54',
        spanId: 'span_54',
        parentSpanId: 'span_53',
        name: 'Database Schema Fetch (Attempt 2)',
        type: 'tool',
        status: 'FAILED',
        latencyMs: 8000,
        tokens: 1200,
        cost: 0.0010,
        retryCount: 2,
        diagnosticTag: 'BAD_TOOL_SCHEMA',
        diagnosticSummary: 'Repeated identical failure: missing foreign key constraints'
      },
      {
        id: 'sp_55',
        spanId: 'span_55',
        parentSpanId: 'span_54',
        name: 'Database Schema Fetch (Attempt 3)',
        type: 'tool',
        status: 'FAILED',
        latencyMs: 8000,
        tokens: 1200,
        cost: 0.0010,
        retryCount: 3,
        diagnosticTag: 'CIRCUIT_BREAKER_KILL',
        diagnosticSummary: 'Circuit breaker triggered: 3 identical tool failures in a loop'
      }
    ]
  },
  {
    id: 'path-6',
    title: '[Demo] Insurance Claim Multi-Source Verification',
    description: 'Cross-checked accident photo metadata, police report OCR text, and policy coverage limits to approve $4,200 payout.',
    status: 'COMPLETED',
    durationMs: 12400,
    tokens: 28400,
    cost: 0.032,
    tps: 167.3,
    elevationDepth: 5,
    modelFamily: 'Claude 3.5 Sonnet',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    project: 'claims-pipeline',
    env: 'production',
    qualityScore: 96,
    version: 'v2.4',
    isDemo: true,
    promptTokens: 8400,
    completionTokens: 20000,
    agent: {
      id: 'agent-research',
      name: 'ResearchAgent',
      framework: 'LangChain',
    },
    spans: [
      {
        id: 'sp_61',
        spanId: 'span_61',
        name: 'Claim Intake Document OCR',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 840,
        tokens: 3200,
        cost: 0.0064
      },
      {
        id: 'sp_62',
        spanId: 'span_62',
        parentSpanId: 'span_61',
        name: 'WebSearch: Accident Report',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 1400,
        tokens: 6400,
        cost: 0.0064
      },
      {
        id: 'sp_63',
        spanId: 'span_63',
        parentSpanId: 'span_62',
        name: 'Database: Policy Lookup',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 280,
        tokens: 1800,
        cost: 0.0036
      },
      {
        id: 'sp_64',
        spanId: 'span_64',
        parentSpanId: 'span_63',
        name: 'Calculator: Damage Assessment',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 120,
        tokens: 800,
        cost: 0.0016
      },
      {
        id: 'sp_65',
        spanId: 'span_65',
        parentSpanId: 'span_64',
        name: 'Approval Letter Generator',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 3200,
        tokens: 16200,
        cost: 0.0140,
        model: 'claude-3.5-sonnet'
      }
    ]
  },
  {
    id: 'path-7',
    title: '[Demo] Full Codebase Security Audit',
    description: 'Scanned 142 repository files for hardcoded secrets, SQL injection vectors, and missing CSRF headers. Created 3 PRs with automated fixes.',
    status: 'COMPLETED',
    durationMs: 89200,
    tokens: 270400,
    cost: 0.840,
    tps: 138.9,
    elevationDepth: 7,
    modelFamily: 'Claude 3.5 Sonnet',
    createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    project: 'security',
    env: 'production',
    qualityScore: 94,
    version: 'v4.0',
    isDemo: true,
    promptTokens: 90000,
    completionTokens: 180400,
    agent: {
      id: 'agent-code',
      name: 'CodeRefactor Agent',
      framework: 'Custom',
    },
    spans: [
      {
        id: 'sp_71',
        spanId: 'span_71',
        name: 'Repository File Manifest Builder',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 1400,
        tokens: 4200,
        cost: 0.0084
      },
      {
        id: 'sp_72',
        spanId: 'span_72',
        parentSpanId: 'span_71',
        name: 'Static AST Security Analyzer',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 24000,
        tokens: 84000,
        cost: 0.2800,
        model: 'claude-3.5-sonnet'
      },
      {
        id: 'sp_73',
        spanId: 'span_73',
        parentSpanId: 'span_72',
        name: 'Vulnerability Impact Classifier',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 18000,
        tokens: 62000,
        cost: 0.1800,
        model: 'claude-3.5-sonnet'
      },
      {
        id: 'sp_74',
        spanId: 'span_74',
        parentSpanId: 'span_73',
        name: 'Automated Patch Generator',
        type: 'llm',
        status: 'SUCCESS',
        latencyMs: 28000,
        tokens: 92000,
        cost: 0.2900,
        model: 'claude-3.5-sonnet'
      },
      {
        id: 'sp_75',
        spanId: 'span_75',
        parentSpanId: 'span_74',
        name: 'GitHub Pull Request Creator',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 3800,
        tokens: 8200,
        cost: 0.0416
      },
      {
        id: 'sp_76',
        spanId: 'span_76',
        parentSpanId: 'span_75',
        name: 'Slack Security Alert Dispatch',
        type: 'tool',
        status: 'SUCCESS',
        latencyMs: 1200,
        tokens: 2000,
        cost: 0.0040
      },
      {
        id: 'sp_77',
        spanId: 'span_77',
        parentSpanId: 'span_76',
        name: 'Audit Report Compilation',
        type: 'chain',
        status: 'SUCCESS',
        latencyMs: 12800,
        tokens: 18000,
        cost: 0.0360
      }
    ]
  }
];

export const MOCK_AGENTS = [
  {
    id: 'agent-code',
    name: 'CodeRefactor Agent',
    framework: 'Custom',
    modelFamily: 'Claude 3.5 Sonnet',
    description: 'Code analysis, test verification, and automated patch generation engine.',
    runs: 3,
    successRate: 67,
    avgLatency: 44667,
    avgCost: 0.324,
    totalCost: 0.972,
    avgTokens: 115667,
    avgQuality: 77,
    recentRuns: [
      { id: 'path-7', title: 'Full Codebase Security Audit', status: 'completed', wallClockMs: 89200, totalCostUsd: 0.840, createdAt: new Date(Date.now() - 3600000 * 36).toISOString() },
      { id: 'path-5', title: 'Microservice Migration Planner', status: 'failed', wallClockMs: 34200, totalCostUsd: 0.094, createdAt: new Date(Date.now() - 3600000 * 18).toISOString() },
      { id: 'path-1', title: 'Resolved Pytest async timeout bug in 12s', status: 'completed', wallClockMs: 12400, totalCostUsd: 0.038, createdAt: new Date(Date.now() - 3600000 * 2).toISOString() },
    ]
  },
  {
    id: 'agent-browser',
    name: 'AutoBrowser Runner',
    framework: 'CrewAI',
    modelFamily: 'GPT-4o',
    description: 'Headless browser automation, DOM selector execution, and interactive form handling.',
    runs: 1,
    successRate: 100,
    avgLatency: 18200,
    avgCost: 0.031,
    totalCost: 0.031,
    avgTokens: 32100,
    avgQuality: 92,
    recentRuns: [
      { id: 'path-2', title: 'Autonomous E-Commerce Checkout Pipeline', status: 'completed', wallClockMs: 18200, totalCostUsd: 0.031, createdAt: new Date(Date.now() - 3600000 * 5).toISOString() },
    ]
  },
  {
    id: 'agent-research',
    name: 'ResearchAgent',
    framework: 'LangChain',
    modelFamily: 'Claude 3.5 Sonnet',
    description: 'Multi-source document synthesis, ArXiv literature review, and market intelligence aggregation.',
    runs: 2,
    successRate: 50,
    avgLatency: 27250,
    avgCost: 0.087,
    totalCost: 0.174,
    avgTokens: 61300,
    avgQuality: 80,
    recentRuns: [
      { id: 'path-6', title: 'Insurance Claim Multi-Source Verification', status: 'completed', wallClockMs: 12400, totalCostUsd: 0.032, createdAt: new Date(Date.now() - 3600000 * 24).toISOString() },
      { id: 'path-3', title: 'Deep Research: Market Analysis Breakdown', status: 'failed', wallClockMs: 42100, totalCostUsd: 0.142, createdAt: new Date(Date.now() - 3600000 * 8).toISOString() },
    ]
  },
  {
    id: 'agent-support',
    name: 'SupportTicket Agent',
    framework: 'LangChain',
    modelFamily: 'GPT-4o',
    description: 'Automated triage, sentiment classification, database customer lookup, and response dispatch.',
    runs: 1,
    successRate: 100,
    avgLatency: 7800,
    avgCost: 0.028,
    totalCost: 0.028,
    avgTokens: 9400,
    avgQuality: 84,
    recentRuns: [
      { id: 'path-4', title: 'Customer Support Ticket Auto-Triage & Response', status: 'completed', wallClockMs: 7800, totalCostUsd: 0.028, createdAt: new Date(Date.now() - 3600000 * 12).toISOString() },
    ]
  }
];

export const MOCK_ANALYTICS = {
  kpis: {
    totalRuns: 7,
    successfulRuns: 5,
    failedRuns: 2,
    runningRuns: 0,
    successRate: 71.4,
    failureRate: 28.6,
    avgLatency: 30314,
    p50Latency: 18200,
    p95Latency: 89200,
    p99Latency: 89200,
    totalTokens: 503100,
    avgTokens: 71871,
    totalPromptTokens: 168800,
    totalCompletionTokens: 334300,
    totalCost: 1.205,
    avgCost: 0.1721,
    avgQuality: 78.5,
  },
  runVolume: [
    { date: '2026-08-17', total: 1, success: 1, failed: 0 },
    { date: '2026-08-18', total: 2, success: 1, failed: 1 },
    { date: '2026-08-19', total: 1, success: 1, failed: 0 },
    { date: '2026-08-20', total: 1, success: 0, failed: 1 },
    { date: '2026-08-21', total: 1, success: 1, failed: 0 },
    { date: '2026-08-22', total: 1, success: 1, failed: 0 },
  ],
  modelUsage: [
    { model: 'Claude 3.5 Sonnet', runs: 4, tokens: 443400, cost: 1.114, avgLatency: 44525 },
    { model: 'GPT-4o', runs: 3, tokens: 59700, cost: 0.091, avgLatency: 11333 }
  ],
  toolUsage: [
    { tool: 'Repository Structure Scanner', calls: 2, successRate: 100, failureRate: 0, avgLatency: 2300, totalCost: 0.0924, retries: 0 },
    { tool: 'Playwright DOM Selector Agent', calls: 2, successRate: 100, failureRate: 0, avgLatency: 9350, totalCost: 0.0158, retries: 0 },
    { tool: 'Database Schema Fetch', calls: 3, successRate: 0, failureRate: 100, avgLatency: 8000, totalCost: 0.0030, retries: 3 },
    { tool: 'WebSearch: ArXiv Papers', calls: 1, successRate: 100, failureRate: 0, avgLatency: 1200, totalCost: 0.0268, retries: 0 },
    { tool: 'WebSearch: Competitor Analysis', calls: 1, successRate: 100, failureRate: 0, avgLatency: 1800, totalCost: 0.0240, retries: 0 },
    { tool: 'Database: Billing Records Lookup', calls: 2, successRate: 50, failureRate: 50, avgLatency: 2770, totalCost: 0.0030, retries: 1 },
    { tool: 'Playwright Sandbox Test Verification', calls: 1, successRate: 100, failureRate: 0, avgLatency: 7600, totalCost: 0.0064, retries: 0 },
    { tool: 'VectorDB Long-Term Memory Recall', calls: 1, successRate: 100, failureRate: 0, avgLatency: 2400, totalCost: 0.0024, retries: 0 }
  ],
  agentStats: [
    { id: 'agent-code', name: 'CodeRefactor Agent', runs: 3, successRate: 67, avgLatency: 44667, avgCost: 0.324, totalCost: 0.972, avgTokens: 115667, avgQuality: 77 },
    { id: 'agent-research', name: 'ResearchAgent', runs: 2, successRate: 50, avgLatency: 27250, avgCost: 0.087, totalCost: 0.174, avgTokens: 61300, avgQuality: 80 },
    { id: 'agent-browser', name: 'AutoBrowser Runner', runs: 1, successRate: 100, avgLatency: 18200, avgCost: 0.031, totalCost: 0.031, avgTokens: 32100, avgQuality: 92 },
    { id: 'agent-support', name: 'SupportTicket Agent', runs: 1, successRate: 100, avgLatency: 7800, avgCost: 0.028, totalCost: 0.028, avgTokens: 9400, avgQuality: 84 }
  ],
  expensiveRuns: [
    { id: 'path-7', title: '[Demo] Full Codebase Security Audit', cost: 0.840, tokens: 270400, duration: 89200, status: 'completed' },
    { id: 'path-3', title: '[Demo] Deep Research: Market Analysis Breakdown', cost: 0.142, tokens: 94200, duration: 42100, status: 'failed' },
    { id: 'path-5', title: '[Demo] Microservice Migration Planner', cost: 0.094, tokens: 58200, duration: 34200, status: 'failed' },
    { id: 'path-1', title: '[Demo] Resolved Pytest async timeout bug in 12s', cost: 0.038, tokens: 18400, duration: 12400, status: 'completed' },
    { id: 'path-6', title: '[Demo] Insurance Claim Multi-Source Verification', cost: 0.032, tokens: 28400, duration: 12400, status: 'completed' },
  ],
  slowestRuns: [
    { id: 'path-7', title: '[Demo] Full Codebase Security Audit', duration: 89200, cost: 0.840, status: 'completed' },
    { id: 'path-3', title: '[Demo] Deep Research: Market Analysis Breakdown', duration: 42100, cost: 0.142, status: 'failed' },
    { id: 'path-5', title: '[Demo] Microservice Migration Planner', duration: 34200, cost: 0.094, status: 'failed' },
    { id: 'path-2', title: '[Demo] Autonomous E-Commerce Checkout Pipeline', duration: 18200, cost: 0.031, status: 'completed' },
    { id: 'path-1', title: '[Demo] Resolved Pytest async timeout bug in 12s', duration: 12400, cost: 0.038, status: 'completed' },
  ]
};

export const MOCK_DETECTIONS = [
  {
    runId: 'path-5',
    runTitle: '[Demo] Microservice Migration Planner',
    runStatus: 'failed',
    detection: {
      type: 'TOOL_LOOP',
      severity: 'CRITICAL',
      title: 'Identical Tool Execution Loop',
      description: 'The agent repeatedly invoked Database Schema Fetch 3 times with identical invalid arguments.',
      evidence: [
        'Span 3: Database Schema Fetch (failed after 8000ms)',
        'Span 4: Database Schema Fetch (failed after 8000ms, retry 2)',
        'Span 5: Database Schema Fetch (circuit breaker tripped, retry 3)'
      ],
      impact: 'Wasted $0.003 and 24.0s of execution time before reaching abort threshold.',
      recommendation: 'Add schema validation interceptor and set max retry backoff limit to 2.'
    }
  },
  {
    runId: 'path-3',
    runTitle: '[Demo] Deep Research: Market Analysis Breakdown',
    runStatus: 'failed',
    detection: {
      type: 'TIMEOUT',
      severity: 'HIGH',
      title: 'Context Drift & LLM Synthesis Timeout',
      description: 'The synthesis step accumulated 94.2k tokens of context, resulting in high latency (>22s) and connection drop.',
      evidence: [
        'Context window expanded to 94,200 tokens across 4 consecutive web search spans',
        'Final LLM call failed to stream after 22,600ms'
      ],
      impact: 'Run failed after consuming $0.142 in token fees.',
      recommendation: 'Introduce an intermediate map-reduce summarization step to cap chunk size below 24k tokens.'
    }
  },
  {
    runId: 'path-4',
    runTitle: '[Demo] Customer Support Ticket Auto-Triage & Response',
    runStatus: 'completed',
    detection: {
      type: 'HIGH_LATENCY',
      severity: 'MEDIUM',
      title: 'Primary DB Lookup Timeout with Failover',
      description: 'Primary database query exceeded timeout threshold (5000ms), triggering fallback replica.',
      evidence: [
        'Span 2: Database Billing Records Lookup exceeded 5200ms latency',
        'Span 3: Replica lookup completed successfully in 340ms'
      ],
      impact: 'Added 5.2s of unnecessary wait time to user interaction.',
      recommendation: 'Optimize index on billing_records(customer_id, status) and lower primary timeout to 1500ms.'
    }
  },
  {
    runId: 'path-7',
    runTitle: '[Demo] Full Codebase Security Audit',
    runStatus: 'completed',
    detection: {
      type: 'TOKEN_EXPLOSION',
      severity: 'LOW',
      title: 'High Token Volume Execution',
      description: 'Run consumed 270,400 tokens across 7 spans, accounting for 55% of all daily tokens.',
      evidence: [
        'AST Security Analyzer consumed 84k tokens in a single prompt',
        'Automated Patch Generator consumed 92k tokens'
      ],
      impact: 'Single run cost $0.840.',
      recommendation: 'Leverage prompt caching for repetitive file trees and AST definitions.'
    }
  }
];

export const MOCK_SESSIONS = [
  {
    sessionId: 'session_code_refactor',
    agentName: 'CodeRefactor Agent',
    modelFamily: 'Claude 3.5 Sonnet',
    turnCount: 4,
    totalTokens: 58400,
    totalCostUsd: 0.124,
    totalDurationMs: 34200,
    status: 'completed',
    lastActiveAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    previewPrompt: 'Fix pytest timeout error in async handler test_auth_flow()',
  },
  {
    sessionId: 'session_browser_scrape',
    agentName: 'AutoBrowser Runner',
    modelFamily: 'GPT-4o',
    turnCount: 2,
    totalTokens: 32100,
    totalCostUsd: 0.031,
    totalDurationMs: 18200,
    status: 'completed',
    lastActiveAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    previewPrompt: 'Purchase item SKU-4821 with express shipping',
  },
  {
    sessionId: 'session_research_ev',
    agentName: 'ResearchAgent',
    modelFamily: 'Claude 3.5 Sonnet',
    turnCount: 6,
    totalTokens: 94200,
    totalCostUsd: 0.142,
    totalDurationMs: 42100,
    status: 'failed',
    lastActiveAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    previewPrompt: 'Analyze EV battery manufacturing cost projections through 2030',
  },
  {
    sessionId: 'session_support_441',
    agentName: 'SupportTicket Agent',
    modelFamily: 'GPT-4o',
    turnCount: 3,
    totalTokens: 9400,
    totalCostUsd: 0.028,
    totalDurationMs: 7800,
    status: 'completed',
    lastActiveAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    previewPrompt: 'Customer inquiry: Requesting pro-rated refund for annual plan billing anomaly',
  }
];
